name = "Hyde My"
license = "MIT"
licenselink = "https://github.com/spf13/hyde/blob/master/LICENSE.md"
description = "An elegant open source and mobile first theme"
tags = ["blog", "company"]
features = ["blog", "themes", "disqus"]
min_version = 0.14

[author]
    name = "osminogin"
    homepage = "http://osminogin.github.io"

# If Porting existing theme
[original]
    name = "spf13"
    homepage = "http://spf13.com"
    repo = "https://github.com/spf13/hyde"
